name: "Fact Flight Info Ingestion"
description: "Ingestion pipeline for data processing and transformation."
version: "1.0.0"

dataset:
  name: "Fact Flight Info"
  description: "Dataset containing Flight information."
  source:
    type: "file"
    url: "file:///datafiles/fact_flight_info.csv"
    encoding: "utf-8"
    delimiter: ","
    quotechar: '"'

datasource:
  driver:
    package: "drivers.postgres_driver"
    class: "PostgresDriver"
    options:
  database:
    drivername: "postgresql+psycopg2"
    name: "data_ontology"
    host: "localhost"
    port: 5432
    options:
      user: "postgres.user"
      password: "postgres.password"
      echo: false
  table:
    name: "fact_flight_info"
    columns: []
    mode: "truncate"
    batch_size: 1000
    options:

modules:
  entry:
    package: "entry.file_entry"
    class: "FileEntry"
  ingestion:
    package: "ingestion.file_ingestion.file_ingestion"
    class: "FileIngestion"
