name: "ingestion"
description: "Ingestion pipeline for data processing and transformation."
version: "1.0.0"

datasets:
  - name: "destinations"
    description: "Dataset containing destination information."
    source:
      type: "api_endpoint"
      url: "https://apigw.singaporeair.com/api/uat/v1/destinations/get"
      method: "POST"
      headers:
        x-csl-client-uuid: "client_uuid"
        x-signature: "client_signature"
        api_key: "api_key"
        options:
          context:
            apiKey: "destination.apiKey"
            secret: "destination.secret"
    options:
      datasource:
        driver:
          module: @module@
          class: @class@
          options:
            tables:
              - name: "destinations"
                columns:
                  - actual: "airportCode"
                    mapped: "f_airport_code"
                    type: "string"
                  - actual: "cityCode"
                    mapped: "f_city_code"
                    type: "string"
                  - actual: "isSQGtwyFlg"
                    mapped: "f_is_sq_gtwy_flg"
                    type: "boolean"
                  - actual: "isTROrigin"
                    mapped: "f_is_tr_ori_flg"
                    type: "boolean"
            batch_size: 1000
            mode: "truncate"

  - name: "availability"
    description: "Dataset containing flight availability, fares and schedules information."
    source:
      type: "api_endpoint"
      url: "https://apigw.singaporeair.com/api/uat/v1/commercial/flightavailability/get"
      method: "POST"
      headers:
        apiKey: "api_key"
        options:
          context:
            apiKey: "search.apiKey"
      body:
        clientUUID: "client_uuid"
        request:
          itineraryDetails:
            - originAirportCode: "{ori_airport_code}"
              destinationAirportCode: "{dest_airport_code}"
              departureDate: "{dep_date}"
              returnDate: "{ret_date}"
          adultCount: "{adult_count}"
          childCount: "{child_count}"
          infantCount: "{infant_count}"
    options:
      datasource:
        driver:
          module: @module@
          class: @class@
          options:
            table_name: "availability"
            batch_size: 1000
            mode: "truncate"